### ISSUE TITLE
TIHabModuleState does not list all modules

### ISSUE THREAD

**Issue by Kazcade** [staehle/tise#4]
The TIHabModuleState listing does not list all hab modules references, but only one reference per hab module. As such, only a single module of any kind can be edited (e.g. only single instance of "Farm" appears in the list despite other "Farms" existing). Given that the references are ordered alphabetically it looks like the browser discards all subsequent references that share the same module name. Is this intended?

**Comment by staehle** [comment]
Oh hey you're right. I haven't played this game since the last release of this, but I still have an old save.

If I look at an item in `TISectorState`, the listed `habModules` values might not exist in `TIHabModuleState`, even though they definitely exist in the save file. Even the "Go to Ref" function doesn't work if I manually enter the value. Huh.

Saving this game results in a significantly smaller file size too, and those IDs disappear. That's a pretty significant bug.

I'll see if I can release a patch quick

**Comment by staehle** [comment]
Thank you @Kazcade for reporting this bug. Try this new release v1.2.0: https://github.com/staehle/tise/releases/tag/v1.2.0

I also added a sort by name or ID feature while I was at it so it should be a little bit easier to use now.

Let me know if that works for you!

**Comment by Kazcade** [comment]
That was...fast. I honestly didn't expect such a prompt fix.

I have tried out the new version and from a cursory testing everything works as expected. I'll let you know should I run into any bugs. Thank you for patching this bug!
